repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - "pytest-cov==4.1.0"
          - "pytest-mock==3.12.0"
          - "pytest-xprocess==0.23.0"
          - "pytest==8.0.1"
          - "resconfig==20.4.3a0"
