repos:
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python
        additional_dependencies: [toml]
