version: 2.1

workflows:
  test:
    jobs:
      - test-install:
          version: "3.11.4"
          coverage: true
      - test-install:
          version: "3.10.12"
      - test-install:
          version: "3.9.17"
      - test-install:
          version: "3.8.17"
      - test-install:
          version: "3.7.17"

  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+.*/
            branches:
              ignore: /.*/
      - test-install:
          version: "3.7"
          requires:
            - build
          filters:
            tags:
              only: /^v\d+.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v\d+.*/
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.11.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "setup.py" }}
            - v2-dependencies-
      - run:
          name: Install dependencies
          command: |
            pip install -e .[test]
      - save_cache:
          key: v2-dependencies-{{ checksum "setup.py" }}
          paths:
            - /home/circleci/versions
      - run:
          name: Run tests
          command: |
            python setup.py tests
      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-install: &test-template
    parameters:
      version:
        type: string
        default: latest
      coverage:
        description: upload coverage report
        type: boolean
        default: false
    docker:
      - image: cimg/python:<< parameters.version >>
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "setup.py" }}
            - v2-dependencies-
      - run:
          name: Install dependencies
          command: |
            pip install -e .[test]
            << parameters.coverage >> && pip install coveralls || :
      - save_cache:
          key: v1-dependencies-{{ checksum "setup.py" }}
          paths:
            - /home/circleci/versions
      - run:
          name: Run tests
          command: |
            python setup.py tests
            << parameters.coverage >> && coveralls || :
      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "setup.py" }}
            - v2-dependencies-
      - run:
          name: Install dependencies
          command: |
            pip install -U pip setuptools twine wheel
            pip install -e .[test]
      - save_cache:
          key: v2-dependencies-{{ checksum "setup.py" }}
          paths:
            - /home/circleci/versions
      - run:
          name: Verify git tag vs. version
          command: |
            version=$(python -c "import socket_log_receiver as m; print(m.__version__)")
            [ v$version = $CIRCLE_TAG ]
      - run:
          name: Create distribution package
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: Upload to pypi
          command: |
            twine upload dist/*
